server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev.datasource.url}
    username: ${dev.datasource.username}
    password: ${dev.datasource.password}
  output:
    ansi:
      enabled: always

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（秒）如果token超过此时间没有访问系统就会被冻结，-1为永不被冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64 等等）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

sms:
  access-key: ${dev.sms.access-key}
  secret-key: ${dev.sms.secret-key}